Market model
labs-13-market-org/Backend pull request #16
Opened 2019-06-06 20:55 UTC by latifahpresident

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2019-06-06 20:59 UTC, txiong000 approved these changes

2019-06-07 01:31 UTC, tactnician requested changes
There are merge conflicts here.  If you see that there is a PR ahead of yours, Pull from the branch that the PR is on and then Push up your changes.. It is the same as Pulling from master because of the merge sequencing..

2019-06-10 02:02 UTC, Sem8 approved these changes

2019-06-10 02:04 UTC, fncischen approved these changes

2019-06-10 14:10 UTC, tactnician approved these changes

2019-06-10 14:11 UTC, tactnician approved these changes

2019-06-10 14:11 UTC, merged